# k8s/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traceassist-backend
  namespace: traceassist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traceassist-backend
  template:
    metadata:
      labels:
        app: traceassist-backend
    spec:
      containers:
        - name: backend
          image: traceassist-backend:latest
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: backend-secret
          ports:
            - containerPort: 8000
