# k8s/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traceassist-frontend
  namespace: traceassist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traceassist-frontend
  template:
    metadata:
      labels:
        app: traceassist-frontend
    spec:
      containers:
        - name: frontend
          image: traceassist-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5173
