apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: traceassist-collector
  namespace: traceassist
spec:
  mode: deployment
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    processors:
      batch: {}
    exporters:
      otlp:
        endpoint: signoz-otel-collector.signoz.svc.cluster.local:4317
    service:
      pipelines:
        traces:
          receivers:
            - otlp
          processors:
            - batch
          exporters:
            - otlp
        metrics:
          receivers:
            - otlp
          processors:
            - batch
          exporters:
            - otlp
