receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  zipkin:
    # Send Zipkin-format spans to Jaeger’s Zipkin listener
    endpoint: "http://jaeger:9411/api/v2/spans"
  prometheus:
    endpoint: "0.0.0.0:9888"
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
